name: Gerar APK Ramon
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Configurar Gradle Manualmente
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.2 # Esta versão resolverá o erro da imagem 2
          
      - name: Compilar APK
        run: gradle assembleDebug
        
      - name: Salvar APK Gerado
        uses: actions/upload-artifact@v4 # Versão corrigida para evitar o erro da imagem 1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
